"""Interactive settings manager.

    python settings.py            # guided setup (first run) or edit menu
    python settings.py --check    # non-interactive: validate current .env
                                  #   (dirs, pattern, API key) and exit

Validates everything before saving: BOOKS_DIR must exist, the book pattern
must match at least one folder, and API keys are tested with a minimal,
free API call. Writes the result to .env and finishes with a confirmation
summary of the books it found.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
ENV_PATH = REPO_ROOT / ".env"

# key, prompt, default, kind ∈ {path, text, regex, int, bool, choice, secret}
FIELDS = [
    ("BOOKS_DIR", "Directory containing your book folders", "~/Writing", "path"),
    ("SERIES_NAME", "Series name (display + collection name)", "My Series", "text"),
    ("BOOK_PREFIX_PATTERN", "Regex that identifies book folders", r"^\d+\.", "regex"),
    ("DATA_DIR", "Where generated data lives", "./data", "text"),
    ("TEXT_EXPORT_DIR", "Pre-exported .txt directory (optional, blank = none)", "", "text"),
    ("EXTRACTION_MODEL", "Model for ingestion metadata (cheap)", "claude-haiku-4-5", "text"),
    ("QUERY_MODEL", "Model for answering questions (capable)", "claude-sonnet-4-6", "text"),
    ("EMBEDDING_PROVIDER", "Embedding provider", "local", "choice:local,openai"),
    ("EMBEDDING_MODEL", "Local embedding model (blank = nomic default)", "", "text"),
    ("ANTHROPIC_API_KEY", "Anthropic API key", "", "secret"),
    ("OPENAI_API_KEY", "OpenAI API key (only for EMBEDDING_PROVIDER=openai)", "", "secret"),
    ("MAX_CHUNK_TOKENS", "Max chunk size in tokens", "800", "int"),
    ("TOP_K_RESULTS", "Chunks retrieved per query", "15", "int"),
    ("CONFIRM_BEFORE_INGEST", "Require confirmation before API spend", "true", "bool"),
    ("LOG_LEVEL", "Log level", "INFO", "choice:DEBUG,INFO,WARNING,ERROR"),
]


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, _, v = line.partition("=")
                values[k.strip()] = v.strip()
    return values


def write_env(values: dict[str, str]) -> None:
    lines = ["# Generated by settings.py — see .env.example for documentation.", ""]
    lines += [f"{key}={values.get(key, default)}" for key, _, default, _ in FIELDS]
    # Keys managed outside this menu (feature flags, tuning knobs) must
    # survive a save — emit them after the managed block.
    known = {key for key, _, _, _ in FIELDS}
    extras = [f"{k}={v}" for k, v in values.items() if k not in known]
    if extras:
        lines += ["", *extras]
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ── validators ──────────────────────────────────────────────────────────────

def find_books(values: dict[str, str]) -> list[str] | str:
    """Matching book folders in order, or an error string."""
    books_dir = Path(os.path.expanduser(values.get("BOOKS_DIR", ""))).resolve()
    if not books_dir.is_dir():
        return f"BOOKS_DIR does not exist: {books_dir}"
    try:
        pattern = re.compile(values.get("BOOK_PREFIX_PATTERN", r"^\d+\."))
    except re.error as e:
        return f"BOOK_PREFIX_PATTERN is not a valid regex: {e}"
    names = [d.name for d in books_dir.iterdir()
             if d.is_dir() and pattern.search(d.name)]
    if not names:
        return ("BOOK_PREFIX_PATTERN matches no folders in "
                f"{books_dir} — adjust the pattern or the directory.")
    def order(name: str) -> int:
        m = re.search(r"\d+", name)
        return int(m.group()) if m else 0
    return sorted(names, key=order)


def check_anthropic_key(key: str) -> str | None:
    """None if the key works; otherwise an error message. Free call."""
    if not key:
        return "ANTHROPIC_API_KEY is empty"
    try:
        import anthropic
        anthropic.Anthropic(api_key=key).models.list(limit=1)
        return None
    except Exception as e:
        return f"Anthropic key test failed: {e}"


def check_openai_key(key: str) -> str | None:
    if not key:
        return "OPENAI_API_KEY is empty (required for EMBEDDING_PROVIDER=openai)"
    try:
        from openai import OpenAI
        OpenAI(api_key=key).models.list()
        return None
    except Exception as e:
        return f"OpenAI key test failed: {e}"


def run_checks(values: dict[str, str], verbose: bool = True) -> list[str]:
    """All validation problems with the given settings (empty = OK)."""
    problems: list[str] = []

    books = find_books(values)
    if isinstance(books, str):
        problems.append(books)
    elif verbose:
        print(f"  ✓ found {len(books)} book folder(s)")

    for key in ("MAX_CHUNK_TOKENS", "TOP_K_RESULTS"):
        try:
            int(values.get(key, "0"))
        except ValueError:
            problems.append(f"{key} must be an integer")

    export_dir = values.get("TEXT_EXPORT_DIR", "").strip()
    if export_dir and not Path(os.path.expanduser(export_dir)).is_dir():
        problems.append(f"TEXT_EXPORT_DIR does not exist: {export_dir}")

    err = check_anthropic_key(values.get("ANTHROPIC_API_KEY", ""))
    if err:
        problems.append(err)
    elif verbose:
        print("  ✓ Anthropic API key works")

    if values.get("EMBEDDING_PROVIDER", "local").lower() == "openai":
        err = check_openai_key(values.get("OPENAI_API_KEY", ""))
        if err:
            problems.append(err)
        elif verbose:
            print("  ✓ OpenAI API key works")

    return problems


# ── interactive flow ────────────────────────────────────────────────────────

def _display(key: str, value: str) -> str:
    if not value:
        return "(blank)"
    if "KEY" in key and len(value) > 12:
        return value[:8] + "…" + value[-4:]
    return value


def prompt_field(key: str, prompt: str, kind: str, current: str) -> str:
    import questionary

    if kind.startswith("choice:"):
        options = kind.split(":", 1)[1].split(",")
        return questionary.select(
            f"{prompt}:", choices=options,
            default=current if current in options else options[0]).ask()
    if kind == "bool":
        return "true" if questionary.confirm(
            f"{prompt}?", default=current.lower() != "false").ask() else "false"
    if kind == "secret":
        answer = questionary.password(
            f"{prompt} (enter to keep {_display(key, current)}):").ask()
        return answer.strip() if answer else current
    answer = questionary.text(f"{prompt}:", default=current).ask()
    return (answer or "").strip()


def interactive(values: dict[str, str]) -> int:
    import questionary

    first_run = not ENV_PATH.exists()
    while True:
        if first_run:
            print("\nWelcome! Let's configure the series RAG system.\n")
            for key, prompt, default, kind in FIELDS:
                values[key] = prompt_field(key, prompt, kind, values.get(key, default))
            first_run = False
        else:
            while True:
                choices = [f"{key} = {_display(key, values.get(key, default))}"
                           for key, _, default, _ in FIELDS] + ["<save and validate>"]
                picked = questionary.select("Edit a setting:", choices=choices).ask()
                if picked is None or picked == "<save and validate>":
                    break
                key = picked.split(" = ")[0]
                _, prompt, default, kind = next(f for f in FIELDS if f[0] == key)
                values[key] = prompt_field(key, prompt, kind, values.get(key, default))

        print("\nValidating…")
        problems = run_checks(values)
        if problems:
            for p in problems:
                print(f"  ✗ {p}")
            if not questionary.confirm("Fix these settings now?", default=True).ask():
                print("Not saved.")
                return 1
            continue

        books = find_books(values)
        print(f"\nFound {len(books)} books in {values['BOOKS_DIR']}:")
        for name in books:
            print(f"  {name}")
        if questionary.confirm("Is this correct?", default=True).ask():
            write_env(values)
            print(f"\nSaved to {ENV_PATH}\nNext: python ingest.py --dry-run")
            return 0
        # user said no -> loop back to the edit menu


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="validate the current .env non-interactively")
    args = ap.parse_args()

    values = read_env(ENV_PATH)
    if args.check:
        if not values:
            print(f"no .env found at {ENV_PATH}")
            return 1
        print("Checking current settings…")
        problems = run_checks(values)
        for p in problems:
            print(f"  ✗ {p}")
        books = find_books(values)
        if isinstance(books, list):
            print(f"  ✓ books: {', '.join(books)}")
        print("OK" if not problems else f"{len(problems)} problem(s)")
        return 0 if not problems else 1

    # defaults for any missing keys
    for key, _, default, _ in FIELDS:
        values.setdefault(key, default)
    return interactive(values)


if __name__ == "__main__":
    sys.exit(main())
